export const TEXT_TITLE = 'Your favourite movies. Explained.'
export const TEXT_SUB_TITLE = 'Figure out what happened. Then find out why.'
export const TEXT_SEARCH_PLACE_HOLDER = 'Search for a movie...'
export const TEXT_EMPTY_MOVIES = 'There is no title related.'
export const TEXT_ERROR_MESSAGE = 'Oops! Something went wrong!'
export const TEXT_NOT_FOUND_MESSAGE = 'Movie not found.'
